import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";

const font = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DockiMoon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        font.className
      )}>
        {children}
      </body>
    </html>
  );
}
